version: '3.8'

services:
  tomcat:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/target/crmtweb.war:/usr/local/tomcat/webapps/ROOT.war
    networks:
      - mynetwork

  db:
    image: postgres
    environment:
      POSTGRES_DB: crmtweb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/CRM-tweb-SQL.sql:/docker-entrypoint-initdb.d/init-db.sql

    ports:
      - "5432:5432"
    networks:
      - mynetwork

  adminer:
    image: adminer
    ports:
      - "5050:8080"
    networks:
      - mynetwork

  angular:
    build: ./frontend
    ports:
      - "4300:80"
    volumes:
      - ./frontend:/app
    # command: ng serve --host 0.0.0.0

volumes:
  postgres_data:
  pgadmin_data:

networks:
  mynetwork: