version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: crmtweb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "5050:8080"

volumes:
  postgres_data:
  pgadmin_data:
